services:
  - type: web
    name: connectly
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py createsu
    startCommand: gunicorn project.wsgi:application
